### ISSUE TITLE
FYI: Exit behavior

### ISSUE THREAD

**Issue by jenbooks** [sqlrob/comicsapp#10]
If you leave the app by switching to another, or by the home button, it remembers your place. If you leave by the back button, it goes to the beginning - whether you go back by the app icon or by recent apps. 

I'M NOT CLAIMING THIS IS A BUG! JUST AN OBSERVATION!

**Comment by sqlrob** [comment]
How would you like it to behave?

**Comment by jenbooks** [comment]
Low priority.

Maybe it should remember your place regardless, with a "first" or "home" button.  Is it possible to make it reset if opened by the app icon?

The "tree" view would make this mostly irrelevant.

**Comment by jenbooks** [comment]
related to bug #16
